---
# - name: Output file list
#   ansible.builtin.debug:
#     msg: "{{ disk_folder.path }}/{{ item | replace('.', '/') | replace(\"['\", '/') | replace(\"']\", '') }}"
#   loop: "{{ data_folders_list.keys() }}"

- name: Create directories inside {{ disk_folder.path }}
  ansible.builtin.file:
    path: "{{ disk_folder.path }}/{{ item | replace('.', '/') | replace(\"['\", '/') | replace(\"']\", '') }}"
    state: directory
    mode: u=rwX,g=rwX,o=rwX
  loop: "{{ data_folders_list.keys() }}"

- name: Set permissions and owner for all files
  become: true
  ansible.builtin.file:
    path: "{{ disk_folder.path }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: u=rwX,g=rwX,o=rwX
    recurse: true
