---
- name: Create and configure folder structure on every drive
  ansible.builtin.include_tasks: filetree-setup.yml
  with_items: "{{ fstab_disks }}"
  when: disk_folder.path | regex_search(".*disk\d$")
  loop_control:
    loop_var: disk_folder
