---
- name: Create filebrowser dir
  ansible.builtin.file:
    path: "{{ container_appdata_path }}/filebrowser"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0700"
    state: directory

- name: Create empty filebrowser.db file
  ansible.builtin.copy:
    content: ""
    dest: "{{ container_appdata_path }}/filebrowser/filebrowser.db"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    force: false
    mode: "0600"
