# Because NVidia-Docker repository use HTTPS,
# apt-transport-https package is necessary.
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
    state: present

- name: Add Nvidia-Docker repository key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add NVidia-Docker repository source
  get_url:
    url: https://nvidia.github.io/nvidia-docker/debian{{ ansible_distribution_major_version }}/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    owner: root
    group: root
    mode: 0644

- name: Install nvidia-docker2
  apt:
    name: nvidia-docker2
    state: present
    update_cache: true
  notify: restart docker

- name: Modify config file to fix issue with debian 11
  ansible.builtin.lineinfile:
    path: /etc/nvidia-container-runtime/config.toml
    regexp: '^ldconfig = "@/sbin/ldconfig"'
    line: 'ldconfig = "/sbin/ldconfig"'
