---
- name: Setup mediaserver docker-compose
  become: true
  block:
    - name: Setup docker-compose-files
      ansible.builtin.include_role:
        name: docker-compose-setup
        public: "yes"
      vars:
        authelia_logo_file: files/assets/logo.png
        authelia_favicon_file: files/assets/favicon.ico

    - name: Setup wireguard
      ansible.builtin.include_tasks: wireguard.yml

    - name: Create mediaserver secrets
      ansible.builtin.include_role:
        name: docker-compose-setup
        tasks_from: secrets.yml
      vars:
        secrets_template_folder: templates/mediaserver-secrets

    - name: Create mediaserver traefik rules
      ansible.builtin.include_role:
        name: docker-compose-setup
        tasks_from: traefik.yml
      vars:
        traefik_rules_dir: templates/mediaserver-traefik/rules

    - name: Ensure appdata directory structure exists
      ansible.builtin.file:
        path: "{{ container_appdata_path }}/{{ item.path }}"
        state: directory
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0755"
      loop: "{{ query('ansible.builtin.filetree', appdata_templates_source) }}"
      when: item.state == 'directory'

    - name: Ensure files are populated from appdata templates
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: '{{ container_appdata_path }}/{{ item.path | regex_replace("\.j2$", "") }}'
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0644"
      loop: "{{ query('ansible.builtin.filetree', appdata_templates_source) }}"
      when: item.state == 'file'

    - name: Create docker-compose.yml file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ docker_dir }}/docker-compose.yml"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0600"

    - name: Create docker-compose env file
      ansible.builtin.template:
        src: .env.j2
        dest: "{{ docker_dir }}/.env"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0600"

    - name: Pull and start docker-compose configuration
      community.docker.docker_compose:
        project_src: "{{ docker_dir }}"
        remove_orphans: true
        pull: true
        state: present
