version: "3.8"

secrets:
    token:
        file: token.txt

services:

    plex:
        image: linuxserver/plex
        container_name: plex
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - VERSION=latest
        volumes:
            - '~/docker/containers/plex/config:/config'
            - '/media/Media:/data'
            - '~/docker/containers/plex/transcode:/transcode'
        network_mode: host
        

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '~/docker/containers/nginx/html:/etc/nginx/html'
            - '~/docker/containers/nginx/config:/etc/nginx'
            - '~/docker/containers/certbot/conf:/etc/letsencrypt'
            - '~/docker/containers/certbot/www:/var/www/certbot'
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - proxies

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - '~/docker/containers/muximux:/config'
        networks:
            - proxies

    tautulli:
        image: linuxserver/tautulli
        container_name: tautulli
        restart: unless-stopped
        environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}
        volumes:
            - '~/docker/containers/tautulli:/config'
            - '~/docker/containers/plex/config/Library/Application Support/Plex Media Server/Logs/:/logs'
        networks:
            - proxies

    beets:
        image: linuxserver/beets
        container_name: beets
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - '~/docker/containers/beets:/config'
            - '/media/Media/Music:/music'
        networks:
            - isolated

    duckdns:
        image: linuxserver/duckdns
        container_name: duckdns
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - SUBDOMAINS=${SUBDOMAINS}
            - FILE__TOKEN=/run/secrets/token
        restart: unless-stopped
        secrets:
            - token
        networks:
            - isolated

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - '~/docker/containers/certbot/conf:/etc/letsencrypt'
            - '~/docker/containers/certbot/www:/var/www/certbot'
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        networks:
            - isolated

    openvpn:
        image: kylemanna/openvpn
        container_name: openvpn
        restart: always
        volumes:
            - '~/docker/containers/openvpn:/etc/openvpn'
        ports:
            - '1194:1194/udp'
        cap_add:
            - NET_ADMIN
        networks:
            - isolated

networks:
    proxies:
        # Containers part of the reverse proxy system
        driver: bridge
    isolated:
        # Containers not part of the reverse proxy system
        driver: bridge
