---
collections:
  - name: devsec.hardening
  - name: community.docker
  - name: community.general

roles:
  - name: grog.package
  - name: geerlingguy.docker
  # Manually added so I could modify
  # - name: ironicbadger.ansible_role_snapraid