---

- name: Setup Mediaserver
  hosts: mediaserver
  become: yes
  roles:
    - grog.package
    - mergerfs
    - snapraid
    - geerlingguy.docker
    - samba
    - name: mediaserver-docker-compose
      become: no
    - name: mediaserver-folders
