---
- import_playbook: setup-common.yml
  vars:
    limit_hosts: nas

- name: Setup nas server
  hosts: nas
  become: true
  roles:
    - name: grog.package
      tags: packages
    - name: common/iptables
      tags: iptables
    - name: nas/mergerfs
      tags: mergerfs
    - name: nas/snapraid
      tags: snapraid
    - name: nas/samba
      tags: samba
    - name: nas/nfs-server
      tags: nfs
    - name: nas/sshfs
      tags: sshfs
    - name: nas/data-folders
      tags: folders
    - name: common/email-setup
      tags: email
    - name: geerlingguy.docker
      tags: docker

- name: Setup docker compose services and files
  hosts: nas
  become: false
  roles:
    - name: docker-services/traefik
    - name: docker-services/wireguard-client
    - name: docker-services/filebrowser
    - name: docker-compose
      tags: docker-compose

- name: Configure nas cron jobs
  hosts: nas
  become: true
  roles:
    - name: common/cron-backup
      vars:
        backup_cron_name: docker-backup
        backup_name_prepend: docker
        backup_destination: "{{ media_data_path }}/.config/backups"
        backup_source: "{{ docker_dir }}"
        backup_max_age_days: "7"
      tags: cron
    - name: common/cron-backup
      vars:
        backup_cron_name: plex-backup
        backup_name_prepend: plex
        backup_destination: "{{ media_data_path }}/.config/backups"
        backup_source: "{{ plex_dir }}"
        backup_max_age_days: "7"
      tags: cron
  tasks:
    - name: Add the /usr/bin and /usr/sbin folders to the cron PATH needed for smartctl
      cron:
        name: PATH
        env: true
        job: /usr/bin:/bin:/usr/bin:/usr/sbin
      tags: cron
    - name: Snapraid SMART emails
      cron:
        name: snapraid scrub
        job: sudo snapraid smart | mail --subject='Snapraid SMART' {{ email_user }}+{{ ansible_hostname }}@gmail.com
        user: root
        weekday: "*"
        minute: "00"
        hour: "00"
        dom: "*"
      tags: cron


- name: Install hd-idle and configure it
  hosts: nas
  become: true
  tags: hd-idle
  tasks:
    - name: Install hd-idle package
      apt:
        name: hd-idle
        state: present

    - name: Append HD_IDLE_OPTS to /etc/default/hd-idle
      lineinfile:
        path: /etc/default/hd-idle
        line: 'HD_IDLE_OPTS="-i 600 -l /var/log/hd-idle.log"'
        create: true

    - name: Touch /var/log/hd-idle.log
      file:
        path: /var/log/hd-idle.log
        state: touch

    - name: Start and enable hd-idle service
      systemd:
        name: hd-idle
        state: started
        enabled: true