---

- import_playbook: setup-common.yml
  vars:
    limit_hosts: mediaserver

- name: Setup Mediaserver
  hosts: mediaserver
  become: true
  roles:
    - name: grog.package
      tags: packages
    - name: common/iptables
      tags: iptables
    - name: mediaserver/mergerfs
      tags: mergerfs
    - name: mediaserver/snapraid
      tags: snapraid
    - name: mediaserver/debian-patched-nvidia-drivers
      tags: nvidia
    # install docker and docker compose
    - name: geerlingguy.docker
      tags: docker
    # then install nvidia module
    - name: mediaserver/nvidia-docker
      tags: docker
    - name: mediaserver/samba
      tags: samba
    - name: common/nfs-server
      tags: nfs
    - name: mediaserver/docker-compose
      become: false
      tags: docker-compose
    - name: mediaserver/data-folders
      tags: folders
    - name: email-setup
      tags: email

      # TODO Refactor to it's own thing to reduce duplicate code in setup-mediabackup.yml
- name: Configure mediaserver CRON jobs
  hosts: mediaserver
  become: true
  roles:
    - name: mediaserver/cron-backup
      vars:
        backup_cron_name: "docker-backup"
        backup_name_prepend: "docker"
        backup_destination: "{{ media_data_path }}/.config/backups"
        backup_source: "/home/{{ primary_user }}/docker"
        backup_max_age_days: '7'
      tags: cron
  tasks:
    - name: Add the /usr/bin and /usr/sbin folders to the cron PATH needed for smartctl
      cron:
        name: PATH
        env: true
        job: /usr/bin:/bin:/usr/bin:/usr/sbin
      tags: cron
    - name: Snapraid SMART emails
      cron:
        name: snapraid scrub
        job: "sudo snapraid smart | mail --subject='Snapraid SMART' {{ email_user }}+{{ ansible_hostname }}@gmail.com"
        user: root
        weekday: "*"
        minute: "00"
        hour: "00"
        dom: "*"
      tags: cron