---

- name: Setup sudo for debian systems
  hosts: all
  roles:
    - debian-sudo

- name: Add ssh keys for user
  hosts: all
  roles:
    - add-ssh-keys

- name: Harden SSH on all systems
  hosts: all
  become: yes
  collections:
    - devsec.hardening
  roles:
    - ssh_hardening
  vars:
    ssh_allow_tcp_forwarding: "yes"

- name: Update all packages
  hosts: all
  become: yes
  roles:
    - update-all-packages
