---
- import_playbook: setup-common.yml
  vars:
    limit_hosts: stormfront

- name: Setup Stormfront
  hosts: stormfront
  become: true
  roles:
    - name: grog.package
      tags: packages
    # install docker and docker compose
    - name: geerlingguy.docker
      tags: docker

- name: Setup docker compose services and files
  hosts: stormfront
  become: false
  roles:
    - name: docker-services/traefik
    - name: docker-services/authelia
    - name: docker-services/wireguard-server
    - name: docker-services/filebrowser
    - name: docker-compose
      tags: docker-compose

- name: Setup secondary user
  hosts: stormfront
  become: true
  tags: create-secondary-user
  tasks:
    - name: Create group {{ secondary_group }}
      group:
        name: "{{ secondary_group }}"
        gid: "{{ secondary_user_guid }}"
        state: present
    - name: Create user {{ secondary_user }}
      user:
        name: "{{ secondary_user }}"
        password: "{{ secondary_user_pass }}"
        group: "{{ secondary_group }}"
        uid: "{{ secondary_user_puid }}"
        shell: /bin/bash
        state: present
    - name: Add "{{ secondary_user }}" ssh key to authorized keys on host
      authorized_key:
        user: "{{ secondary_user }}"
        key: "{{ secondary_user_ssh_identity_key }}"

- name: Setup share folder
  hosts: stormfront
  become: true
  tags: setup-share
  tasks:
    - name: Create share dir
      file:
        path: /home/share
        owner: "{{ primary_user }}"
        group: "{{ primary_group }}"
        mode: "0777"
        recurse: true
        state: directory
    - name: Sets default ACL share folder
      ansible.posix.acl:
        path: /home/share
        etype: mask
        permissions: rwX
        recursive: true
        default: true
        state: present
    - name: create directory symlinks
      file:
        src: /home/share
        dest: /home/{{ item }}/share
        owner: "{{ item }}"
        group: "{{ item }}"
        state: link
      loop:
        - "{{ primary_user }}"
        - "{{ secondary_user }}"

- name: Setup remote fileshare ssh access
  hosts: stormfront
  become: true
  tags: setup-remote
  tasks:
    - name: Add "remote_fileshare" ssh key to authorized keys on host
      authorized_key:
        user: "{{ ssh_user }}"
        key: "{{ remote_ssh_identity_key }}"
