---

- name: Setup Mediaserver
  hosts: mediaserver
  become: yes
  roles:
    - name: grog.package
      tags:
        - always
        - packages
    - name: mergerfs
      tags:
        - mergerfs
    - name: snapraid
      tags: snapraid
    - name: iptables
      tags: iptables
    - name: geerlingguy.docker
      tags: docker
    - name: samba
      tags: samba
    - name: mediaserver-docker-compose
      become: no
      tags: docker-compose
    - name: mediaserver-folders
      tags: folders
    - name: email-setup
      tags: email

- name: Configure mediaserver
  hosts: mediaserver
  become: yes
  roles:
    - name: cron-backup
      vars:
        backup_cron_name: "docker-backup"
        backup_name_prepend: "docker"
        backup_destination: "{{ media_data_path }}/.config/backups"
        backup_source: "/home/{{ primary_user }}/docker"
        backup_max_age_days: '7'
      tags: cron
  tasks:

    - name: Add the /usr/bin and /usr/sbin folders to the cron PATH needed for smartctl
      cron:
        name: PATH
        env: yes
        job: /usr/bin:/bin:/usr/bin:/usr/sbin
      tags: cron
    - name: Snapraid SMART emails
      cron:
        name: snapraid scrub
        job: "snapraid smart | mail --subject='Snapraid SMART' {{ email_user }}+{{ ansible_hostname }}@gmail.com"
        user: root
        weekday: "*"
        minute: "00"
        hour: "00"
        dom: "*"
      tags: cron
