---
- name: Update all packages on Debian based systems
  when: ansible_facts['os_family'] == "Debian"
  become: true
  block:
    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
        cache_valid_time: 3600

    - name: Remove packages not needed anymore
      ansible.builtin.apt:
        autoremove: true

    - name: Check if a reboot is needed
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: false

    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible for kernel updates
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
