---
# Followed guide here: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
# Because NVidia-Docker repository use HTTPS,
# apt-transport-https package is necessary.
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present

- name: Add NVIDIA Container Toolkit repository key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present

- name: Add NVIDIA Container Toolkit repository source
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    owner: root
    group: root
    mode: "0644"

- name: Install nvidia-container-toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
    update_cache: true
  notify: Restart docker
