---
media_data_path: /data

docker_compose_file: "/home/{{ primary_user }}/docker"
container_appdata_path: "{{ docker_compose_file }}/appdata"

traefik_directory: "{{ container_appdata_path }}/traefik"

compose_puid: 1000
compose_guid: 1000
compose_tz: America/Denver

route53__access_key: ""
route53_secret_access_key: ""
route53_zone_id: ""