apiVersion: v2
name: traefik
description: Reverse proxy for managing apps and routing
type: application
version: 0.1.0
dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: v41.0.0