---
- name: Create directories inside {{ disk_folder.path }}
  ansible.builtin.file:
    path: "{{ disk_folder.path }}/{{ new_folder.path }}"
    state: directory
    mode: u=rwX,g=rwX,o=rwX
  loop: "{{ query('ansible.builtin.filetree', disk_folder.path) }}"
  loop_control:
    loop_var: new_folder
  when: new_folder.state == "directory"

- name: Set permissions and owner for all files
  become: true
  ansible.builtin.file:
    path: "{{ disk_folder.path }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: u=rwX,g=rwX,o=rwX
    recurse: true
