---
# Update and install packages for hassio and docker  ------------------------ #
- name: Update all packages to their latest version
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    autoremove: true

- name: Install packages for hassio and docker
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - ca-certificates
    - gnupg
    - apparmor
    - jq
    - wget
    - curl
    - udisks2
    - libglib2.0-bin
    - network-manager
    - dbus
    - systemd-journal-remote

# Install docker ------------------------------------------------------------- #
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian/ {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Set docker cgroup to v1
  ansible.builtin.lineinfile:
    backup: true
    backrefs: true
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=(false|1) quiet"$
    line: GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=0 quiet"
  notify: Update grub

# Install hassio ------------------------------------------------------------- #
- name: Install hassio OS Agent
  ansible.builtin.apt:
    deb: "{{ os_agent_deb_path }}"

- name: Install hassio supervised installer
  ansible.builtin.apt:
    deb: "{{ supervised_installer_deb_path }}"
