---
- name: Comment out enterprise repositories
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: ^(deb .* enterprise)$
    line: "# \\1"
    backrefs: true
    firstmatch: true
  loop:
    - "{{ no_subscription_ceph_repo }}"
    - "{{ no_subscription_pve_repo }}"

- name: Append no-subscription ceph repo
  ansible.builtin.lineinfile:
    path: "{{ no_subscription_ceph_repo.path }}"
    line: "{{ no_subscription_ceph_repo.repo }}"
    state: present
    create: true
    mode: "0644"

- name: Append no-subscription pve repo
  ansible.builtin.lineinfile:
    path: "{{ no_subscription_pve_repo.path }}"
    line: "{{ no_subscription_pve_repo.repo }}"
    state: present
    create: true
    mode: "0644"

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
