---
- name: Install mergerfs
  ansible.builtin.package:
    name: mergerfs
    state: present

- name: Mount hard drives
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    passno: "{{ item.passno | default('0') }}"
    state: mounted
  loop: "{{ fstab_disks }}"
  become: true
  when: item.src is defined and item.path is defined and item.fstype is defined
