# roles/iptables/tasks/main.yml
- block:
  - name: Set default iptables head rules
    iptables_raw:
      name: iptables_default_head
      weight: 10
      keep_unmanaged: '{{ iptables_keep_unmanaged }}'
      state: present
      rules: '{{ iptables_default_head }}'

  - name: Set custom iptables rules
    iptables_raw:
      name: 'iptables_custom_rules_{{ item.name }}'
      rules: '{{ item.rules }}'
      state: '{{ item.state }}'
      weight: '{{ item.weight|default(omit) }}'
      table: '{{ item.table|default(omit) }}'
    with_items: '{{ iptables_custom_rules }}'
    when: iptables_custom_rules|length > 0
    notify:
      - Save iptables config
      - Restart docker service