---

all:
  children:
    hypervisors:
      hosts:
        nas:
        nuk:   # Hardware Accelerated MediaPC
        crypt: # Backup NAS

    k3s_cluster:
      children:
        server:
          hosts:
            k3s-server-01: 
      vars:
        k3s_version: v1.31.12+k3s1
        token: "{{ k3s_token }}"
        api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
        cluster_context: samurai-cluster
        server_config_yaml:  |
          disable:
            - traefik


    services:
      hosts:
        mediaserver: # Legacy media vm on nas
        media:  # Plex LXC on nuk
        rakugo: # docker setup on nuk
        homeassistant: # 
        dev: # vscode and other dev tools on nas

    external:
      hosts:
        stormfront:
          ansible_host: storm.cobaltcavern.com
          vars:

  vars:
    ansible_user: "{{ primary_user }}"
    ansible_become_pass: '{{ vault_become_pass }}'
    ansible_host: '{{ inventory_hostname }}.{{ local_domain }}'
    
