---
- name: Apply standard config
  hosts: nuk
  become: true
  tags: common-config
  tasks:
    - name: Create user {{ primary_user }}
      ansible.builtin.user:
        name: "{{ primary_user }}"
        password: "{{ primary_user_pass_encoded }}"
        uid: "{{ primary_user_puid }}"
        shell: /bin/bash
        state: present
      tags: create-user

- name: Run common roles
  hosts: nuk
  become: true
  tags:
    - common-config
    - init
  roles:
    - role: proxmox/use-no-subscription-repos # noqa: role-name[path]
    - role: common/debian-sudo # noqa: role-name[path]
    - role: common/add-ssh-keys # noqa: role-name[path]
      become: true
      tags: ssh
    - role: devsec.hardening.ssh_hardening
      vars:
        ssh_allow_tcp_forwarding: "yes"
        # ssh_server_password_login: true
        # sshd_authenticationmethods: publickey password
      tags: ssh
    - role: common/update-all-packages # noqa: role-name[path]
      tags: packages
    - role: grog.package
      tags: packages

- name: Provision OpenTofu Service Account
  hosts: nuk
  become: true
  roles:
    - role: proxmox/tofu-setup # noqa: role-name[path]
      tags: tofu-setup

- name: Build Debian Cloud-Init Template
  hosts: nuk
  tags:
    - template
    - cloud-init
  roles:
    - role: proxmox/debian-template # noqa: role-name[path]
