---
- name: Ensure NFS utilities are installed
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure directories to export exist
  ansible.builtin.file: # noqa 208
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Configure /etc/default/nfs-common
  ansible.builtin.template:
    src: nfs-kernal-server.j2
    dest: /etc/default/nfs-common
    owner: root
    group: root
    mode: "0644"

- name: Configure /etc/default/nfs-kernal-server
  ansible.builtin.template:
    src: nfs-kernal-server.j2
    dest: /etc/default/nfs-kernal-server
    owner: root
    group: root
    mode: "0644"

- name: Copy exports file
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Reload nfs

- name: Ensure nfs is running
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: true
  when: nfs_exports | length > 0
