


# Packages and installation
# -----------------------------

# .. envvar:: samba__base_packages
#
# List of base packages to install.
# In case you only want to prepare the host for being a Samba client, remove
# the ``samba`` package from the list. This might be required because
# applications like ownCloud depend on the :command:`smbclient` which gets things like
# workgroup from the file :file:`/etc/samba/smb.conf`.
samba__base_packages:
  - 'samba'
  - 'samba-common'
  - 'samba-common-bin'


# Firewall configuration
# --------------------------




# Global Samba options
# ------------------------

# .. envvar:: samba__workgroup
#
# This controls what workgroup your server will appear to be in when queried by
# clients. Note that this parameter also controls the Domain name used with the::
#
#    samba__security: 'domain'
#
# setting.
samba__workgroup: 'WORKGROUP'


# .. envvar:: samba__security
#
# This option affects how clients respond to Samba and is one of the most
# important settings in the :file:`/etc/samba/smb.conf` file.
samba__security: 'user'


# .. envvar:: samba__netbios_name
#
# This sets the NetBIOS name by which a Samba server is known. By default it is
# the same as the first component of the host's DNS name. If a machine is a
# browse server or logon server this name (or the first component of the hosts
# DNS name) will be the name that these services are advertised under.
samba__netbios_name: '{{ ansible_hostname }}'


# .. envvar:: samba__server_string
#
# This controls what string will show up in the printer comment box in print
# manager and next to the IPC connection in net view. It can be any string that
# you wish to show to your users.
# It also sets what will appear in browse lists next to the machine name.
#
# A ``%v`` will be replaced with the Samba version number.
#
# A ``%h`` will be replaced with the hostname.
samba__server_string: '%h file server'


# .. envvar:: samba__service_name
#
# Name of the /etc/init.d/ service script
samba__service_name: 'samba'


# .. envvar:: samba__name_resolve_order
#
# Resolve order of Samba.
samba__name_resolve_order: 'lmhosts host wins bcast'


# .. envvar:: samba__default_global
#
# Default ``[global]`` configuration.
samba__default_global:

  # Browsing / Identification.
  workgroup: '{{ samba__workgroup }}'
  netbios_name: '{{ samba__netbios_name }}'
  server_string: '{{ samba__server_string }}'

  # Logs / Accounting.
  log_file: '/var/log/samba/log.%m'
  max_log_size: '1000'
  syslog: '0'

  # Authentication.
  security: '{{ samba__security }}'
  encrypt_passwords: 'yes'
  passdb_backend: 'tdbsam'
  unix_password_sync: 'no'
  obey_pam_restrictions: 'yes'
  invalid_users: 'root bin daemon adm sync shutdown halt mail news uucp proxy www-data backup sshd'
  map_to_guest: 'never'
  guest_account: 'nobody'

  # File system / Directories.
  unix_charset: 'UTF8'
  locking: 'yes'
  wide_links: 'no'
  browseable: 'yes'
  create_mask: '0660'
  directory_mask: '0770'
  dont_descend: './lost+found'
  use_sendfile: 'yes'
  hide_unreadable: 'yes'
  hide_files: '/.*/lost+found/'

  # Networking / Connections.
  socket_options: 'TCP_NODELAY'
  deadtime: '10'
  wins_support: 'no'
  dns_proxy: 'no'
  name_resolve_order: '{{ samba__name_resolve_order }}'

  # Disable printing by default.
  printing: 'bsd'
  load_printers: 'no'
  printcap_name: '/dev/null'
  show_add_printer_wizard: 'no'
  disable_spoolss: 'yes'


# .. envvar:: samba__global
#
# Which hash variable is used to configure the ``[global]`` section in
# :file:`/etc/samba/smb.conf`.
samba__global: '{{ samba__default_global }}'


# .. envvar:: samba__global_custom
#
# You can specify additional options in a separate hash.
samba__global_custom: {}


# Network shares
# ------------------


# .. envvar:: samba__shares
#
# Which hash of hashes is used to configure shares in
# :file:`/etc/samba/smb.conf`.
samba__shares: '{{ samba__default_shares }}'


# .. envvar:: samba__default_shares
#
# Hash of hashes of default shares.
samba__default_shares:

  'Public Files':
    path: '/public'
    comment: 'Public Files'
    read_only: 'yes'
    guest_ok: 'yes'
