---
- name: Create trafick acme dir
  ansible.builtin.file:
    path: "{{ traefik_directory }}/acme"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    force: false
    mode: "0700"
    state: directory

- name: Ensure 'traefik/acme/acme.json' exists
  ansible.builtin.copy:
    content: ""
    dest: "{{ traefik_directory }}/acme/acme.json"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    force: false
    mode: "0600"

- name: Install logrotate
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Create traefik logs dir
  ansible.builtin.file:
    path: "{{ traefik_directory }}/logs"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0750"
    state: directory

- name: Install traefik logrotate config
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/traefik
    owner: root
    group: root
    mode: "0644"
    validate: logrotate -d %s

- name: Create trafick rules dir
  ansible.builtin.file:
    path: "{{ traefik_directory }}/rules"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0700"
    state: directory

- name: Create trafik rules
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_directory }}/rules/{{ item | basename | regex_replace('.j2', '') }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0600"
  with_fileglob:
    - "{{ traefik_rules_dir }}/*.j2"
