---
- name: Create folder for vpn container
  ansible.builtin.file:
    path: "{{ container_appdata_path }}/wireguard/"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0700"
    state: directory

- name: Add wireguard conf file for container
  ansible.builtin.copy:
    src: "{{ inventory_hostname }}/vault/wg0.conf"
    dest: "{{ container_appdata_path }}/wireguard/wg0.conf"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0600"
