---
samba__workgroup: samurai
samba__server_string: Meets all your consumption requirements! Money back Garuntee!

samba__default_global:
  # Browsing / Identification.
  workgroup: "{{ samba__workgroup }}"
  netbios_name: "{{ ansible_hostname }}"
  server_string: "{{ samba__server_string }}"

  # Logs / Accounting.
  log_file: /var/log/samba/log.%m
  max_log_size: "1000"
  log_level: 2

  # Authentication.
  security: user

  # Windows 11 hardening
  server_signing: mandatory
  server_smb_encrypt: desired
  server_min_protocol: SMB3
    
  # Microsoft Account Support
  username map: /etc/samba/smbusers

  passdb_backend: tdbsam
  unix_password_sync: "false"
  obey_pam_restrictions: "yes"

  # Security
  invalid_users: root bin daemon adm sync shutdown halt mail news uucp proxy www-data backup sshd
  guest_account: nobody
  map_to_guest: Bad User

  # File system / Directories.
  unix_charset: UTF8
  locking: "yes"
  wide_links: "false"
  browseable: "yes"
  create_mask: "0660"
  directory_mask: "0770"
  use_sendfile: "yes"
  hide_unreadable: "yes"

  # Networking / Connections.
  deadtime: "10"
  wins_support: "false"
  dns_proxy: "false"
  name_resolve_order: "{{ samba__name_resolve_order }}"

  # Disable printing by default.
  printing: bsd
  load_printers: "no"
  printcap_name: /dev/null
  show_add_printer_wizard: "no"
  disable_spoolss: "yes"

samba__shares:
  Media:
    path: /data
    comment: Media
    read_only: false
    guest_ok: false
    force_user: nobody
    force_group: nogroup
    create_mask: "0666"
    directory_mask: "0777"

  data:
    path: /data
    comment: Same as Media added for PKC convienience
    read_only: false
    guest_ok: true
    force_user: nobody
    force_group: nogroup
    create_mask: "0666"
    directory_mask: "0777"
