---
- name: Get iptables_save output
  ansible.builtin.shell: iptables-save
  register: iptables_save_output

- name: Copy the output to a local file
  ansible.builtin.copy:
    content: "{{ iptables_save_output.stdout }}"
    mode: "0644"
    dest: /etc/iptables/rules.v4
