---
- name: Setup docker-compose files
  become: true
  tags: compose-setup
  block:

    - name: Setup secrets
      ansible.builtin.include_tasks: secrets.yml

    - name: Ensure appdata directory structure exists
      ansible.builtin.file:
        path: "{{ container_appdata_path }}/{{ item.path }}"
        state: directory
        mode: "0755"
      loop: "{{ query('ansible.builtin.filetree', appdata_templates_source) }}"
      when: item.state == 'directory'

    - name: Ensure files are populated from appdata templates
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: '{{ container_appdata_path }}/{{ item.path | regex_replace("\.j2$", "") }}'
        mode: "0644"
      loop: "{{ query('ansible.builtin.filetree', appdata_templates_source) }}"
      when:
        - item.state == 'file'
        - item.path.endswith('.j2')

    - name: Copy appdata files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: '{{ container_appdata_path }}/{{ item.path }}'
        mode: "0644"
      loop: "{{ query('ansible.builtin.filetree', appdata_templates_source) }}"
      when:
        - item.state == 'file'
        - not item.path.endswith('.j2')

- name: Setup docker-compose files
  become: true
  block:
    - name: Ensure compose directory structure exists
      ansible.builtin.file:
        path: "{{ docker_dir }}/{{ item.path }}"
        state: directory
        mode: "0755"
      loop: "{{ lookup('community.general.filetree', role_template_source) +
                lookup('community.general.filetree', docker_templates_source) }}"
      when: item.state is defined and item.state == 'directory'

    - name: Ensure files are populated from compose templates
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: '{{ docker_dir }}/{{ item.path | regex_replace("\.j2$", "") }}'
        mode: "0644"
      loop: "{{ lookup('community.general.filetree', role_template_source) +
                lookup('community.general.filetree', docker_templates_source) }}"
      when:
        - item.state is defined and item.state == 'file'
        - item.path.endswith('.j2')

    - name: Pull and start docker-compose configuration
      community.docker.docker_compose_v2:
        project_src: "{{ docker_dir }}"
    #  register: output

    # - name: Show results
    #   ansible.builtin.debug:
    #     var: output
