---

- name: Create secrets directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/secrets"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0700"
    state: directory

- name: Create secrets files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ container_secrets_path }}{{ item | basename | regex_replace('.j2', '') }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0700"
  loop: "{{ query('ansible.builtin.filetree', secrets_template_folder) }}"
  when: item.state == 'directory'

- name: Ensure files are populated from appdata templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: '{{ container_secrets_path }}/{{ item.path | regex_replace("\.j2$", "") }}'
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0600"
  loop: "{{ query('ansible.builtin.filetree', secrets_template_folder) }}"
  when: item.state == 'file'
