---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-route53-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgCCsQOq0MImzAH349CiB/zRNjNmMaKTwZmF56rgFl/oPZHUujsRWmiiubsj2FHuZqIDzRQt+m5ikEZImu8u8nmvgGsXjCmpMoDVOu7cPD+u10mjd3uBdI6Rns5jy0W8KQ7+rb02KWuBpj7blRv9xqb8XsqxQjCLF2oFVxjpXCOGmICrd9Zfv1kyfvfh9tXR+A/ESUD+tzSBMpUF58tKqBrSrO4YkXhbrduGxmvAQyEYnso1CY5EJ9lmGc55jr2WliWbva3hpBa92pyoFPmn1CvUtpWTW41GogZ2aPWZWdraOqbRnV3JbYaydx3Ea3Ft98m3hul5jctU0jfO7GnXIsOSvUaLugUN6lNwXSr7Udd6sr1W49yncvmHe9rO7ezHEAYwZqs50gokYeWV0ibuw4JfSuzAcpy3w14TSJIDZXZ4eKIgi0XIkSP3n+Rhkkl47JhblZ70FqIdboFQmKIO5nA/aAt/T1sEFGwduI7M5TXqhihDT1BQM6qwqTrQ1OySvs11fSk90+jxEERaELMHI6lhNfJRA3o6lHc/x/LHYlZv3aAjz8Lfxnj24gNXNFYM9OuoC2TvZwzQtUMa47+IDW653ETkUvSoD/XUfOq2vakBmdAmVid2FChsO102y8/q9m7tNuU7EDXp9fyZkouctKCMTDHskeefnyF26U9j9R4xF6Gew5w/a5F7+5wFgVUf/xD//USW9V6kt6U6jgWDJVIAmL+fu/cHA8sWYrJ9D0oAZzec1itst22Z
  template:
    metadata:
      name: aws-route53-secret
      namespace: cert-manager
