---
docker_dir: /opt/docker
container_appdata_path: "{{ docker_dir }}/appdata"

docker_user: root
docker_group: root
compose_puid: 0
compose_guid: 0
compose_tz: America/Denver

route53__access_key: ""
route53_secret_access_key: ""
route53_zone_id: ""

# Basic Auth
primary_user_htpass: ""

# Oauth
oauth_client_id: ""
oauth_client_secret: ""
forward_auth_secret: ""
