---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgC9WnGBxNhIX/N9Aeho/Dhmmat8ak8z1dbkfhQZNKZv1HyV/XUvAT2cU9RQtT0PBPsuz+da1Sd4a/UVCUP9U0r380Licjn5NROV+ulspIMV2WkAvGWcZ+xZlvQpCuJiW/JpagTZMwt3tEw1qsRCzUF/Tlfu5bulavuONsNCju6TNStCy1sY7SSodiHw/OXkwYYrrNZinQTfoH2ApiSOKrEFJsexnep1FoooT1R0l0PYcSc8VSpQtKXfGDDzdF6A7hybp5BqAwTZGPsQIeqwyifkuWM12fsldJ1FE4iNTEXBy8B50eFs/bigiWLYrw+G7/cN/S/vuU51mLC/hW1AIY5yTcgWNUNxJXuqDB3HxQFcmTf5o2VkmdjYkm/THDORxXC0nS2qNwO1n+EGINiiR1Li0JbQux0mUxtQ8X+30SzwukxHXNTgt6WcRgZORLhaF3AJWmttlZG+jEJMYBLDVXdukqA/31Pz9R6XGI+qwdy7jf0ZClPBLuq2bg4HSNvZ15WabBf31+2cnM/IkoNyWdf/GhcB/pi9XxGyUOCwBHbYs7z0C13YE+cE1Fb3Zf+qVbclU10WNNCrYf1x18TwcObSafrI+JPPYdhVAveaprlw9PuQWKq8qI3V8PB5x429hJLzTvpV4aF38S9IJNSZZOxuFB1xMsSq43IXDSfk2ypcEGPWMY8OixgMjQtQsMM5vMYgpNjuzlDH9Z3S+mD9LFIaVh9iYgBrLwM2faHRxkBmszmb2KnhykVW
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
