---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgBw72hkHMg5ksXqE5eIfIrfFn+qlM4CW4MbL3FRVifjWgrDpzVX9SRjXsGZ8OjWhtQwxOQL3EqRkFjn9q5JXKWBRvkySKIkVqQ4Uy/cCWonZ6b0I+KOfXjeImds1j78adFozSyWXAHTMZi5FK1qiDYQ2nQySU/W2U1k1YARibIuQsLlXVx5sAY42B8PIUQloxgCqYS+clLh5GRMXLusD3IS91O+UDKFcxOcnlfUWBXAoyx/fL6cSQ6a0IS5imrOMjNwU3Wz/kiMMg4FhaHFwKEnpSpDOQROH3IoZqUJMy2/z0TkNd3U7jW8ACwbbV+QPIonQX98wDGTGvxx1uoD0kFOgM6YsxSIZvGQEvDRJCxSSdlJOou6t0GUPVXUuASei1vZtfHSwRDtoChGNj5KIBJ99rWmjQ1vN0QhpkNhNgWxkxbhYU6Ofhvtclz8dc7oGjbfn9g2xTfGSdMsxpEc3QGfciP9Iy0nwHdp7ndhQu/n5xuRqs0qZrac0sthZxQMhv+AU6rEjT1M6MbFOI+MA2iXTrZKqWh4jH2cD5VNWPXAIigYoh5MfORN/0JKbyYUKMsGJjZp9HH4ovBA0Gb88gRbF2NUGO3LbS68MCKDQHl5ls+0P97U28ad5gh6axX1aD/q5zsshTpqJuAiz0TUrjzMMv0oRAev/WbpgaIZP9xScjigX9Ca6d+d4kYde6Sk4B5vJDIIFA+h5cVlQa909+hwiFMhkp/VROqokgv+/EdWppxct0DHL2bnmg==
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
