---

- include: secrets.yml
- include: vpn.yml
- include: traefik.yml
- include: authelia.yml

- name: Set container folder user permissions
  file:
    dest: "{{ container_data_path }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: "u+rwX,g-w,o-w"
    recurse: yes
  become: yes

- name: Setup docker-gc-exclude
  get_url:
    url: https://raw.githubusercontent.com/clockworksoul/docker-gc-cron/master/compose/docker-gc-exclude
    dest: "{{ container_data_path }}/docker-gc/docker-gc-exclude"
    mode: 0644

- name: install docker pip modules
  pip:
    name: docker-compose
    state: present

- name: Create docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    mode: 0644

- name: Create docker-compose env file
  template:
    src: .env.j2
    dest: "{{ docker_compose_path }}/.env"
    mode: 0644

- name: Pull and start docker-compose configuration
  community.docker.docker_compose:
    project_src: "{{ docker_compose_path }}"
    remove_orphans: yes
    pull: yes
    state: present
