- name: Create 'docker/secrets' dir
  file:
    path: "{{ docker_compose_path }}/secrets"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: 0700
    state: directory

- name: Create secrets/htpasswd file
  template:
    src: secrets/htpasswd.j2
    dest: "{{ docker_compose_path }}/secrets/htpasswd"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: 0600

- name: Create secrets/traefik_forward_auth file
  template:
    src: secrets/traefik_forward_auth.j2
    dest: "{{ docker_compose_path }}/secrets/traefik_forward_auth"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: 0600