---
- name: Create trafick dirs
  file:
    path: "{{ traefik_directory }}/acme"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: '0755'
    state: "directory"

- name: Ensure acme config
  file:
    path: "{{ traefik_directory }}/acme/acme.json"
    state: touch
    mode: '0600'

- name: Ensure traefik log
  file:
    path: "{{ traefik_directory }}/traefik.log"
    state: touch
    mode: '0755'
