---
- name: Create trafick dirs
  file:
    path: "{{ traefik_directory }}/acme"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: '0755'
    state: "directory"

- name: Ensure 'traefik/acme/acme.json' exists
  copy:
    content: ""
    dest: "{{ traefik_directory }}/acme/acme.json"
    force: no
    mode: '0600'

- name: Ensure 'traefik/traefik.log' exists
  copy:
    content: ""
    dest: "{{ traefik_directory }}/traefik.log"
    force: no
    mode: '0755'

- name: Create 'traefik/rules/middlewares.yml' file
  template:
    src: traefik/rules/middlewares.yml.j2
    dest: "{{ traefik_directory }}/rules/middlewares.yml"
    mode: 0644

- name: Create 'traefik/tls-opts.yml' file
  template:
    src: traefik/rules/tls-opts.yml.j2
    dest: "{{ traefik_directory }}/rules/tls-opts.yml"
    mode: 0644

- name: Create 'traefik/rules/middleware-chains.yml' file
  template:
    src: traefik/rules/middleware-chains.yml.j2
    dest: "{{ traefik_directory }}/rules/middleware-chains.yml"
    mode: 0644
