- name: create folder for vpn container
  file:
    path: "{{ container_data_path }}/vpn/"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: '0755'
    state: "directory"

- name: add ovpn file for vpn container
  copy:
    src: files/vault/vpn.ovpn
    dest: "{{ container_data_path }}/vpn/vpn.ovpn"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: '0644'