---
samba__workgroup: samurai
samba__server_string: Meets all your consumption requirements! Money back Garuntee!

samba__default_global:
  # Browsing / Identification.
  workgroup: "{{ samba__workgroup }}"
  netbios_name: "{{ ansible_hostname }}"
  server_string: "{{ samba__server_string }}"

  # Logs / Accounting.
  log_file: /var/log/samba/log.%m
  max_log_size: "1000"
  syslog: "0"

  # Authentication.
  security: user
  encrypt_passwords: "yes"
  passdb_backend: tdbsam
  unix_password_sync: "no"
  obey_pam_restrictions: "yes"
  invalid_users: root bin daemon adm sync shutdown halt mail news uucp proxy www-data backup sshd
  valid users: nobody
  map_to_guest: bad user
  guest_account: nobody

  # File system / Directories.
  unix_charset: UTF8
  locking: "yes"
  wide_links: "no"
  browseable: "yes"
  create_mask: "0660"
  directory_mask: "0770"
  dont_descend: ./lost+found
  use_sendfile: "yes"
  hide_unreadable: "yes"
  hide_files: /.*/lost+found/

  # Networking / Connections.
  socket_options: TCP_NODELAY
  deadtime: "10"
  wins_support: "no"
  dns_proxy: "no"
  name_resolve_order: "{{ samba__name_resolve_order }}"

  # Disable printing by default.
  printing: bsd
  load_printers: "no"
  printcap_name: /dev/null
  show_add_printer_wizard: "no"
  disable_spoolss: "yes"

samba__shares:
  Media:
    path: /data
    comment: Media
    read only: false
    guest ok: true
    force user: nobody
    create mask: 666
    directory mask: 777

  data:
    path: /data
    comment: Same as Media added for PKC convienience
    read only: false
    guest ok: true
    force user: nobody
    create mask: 666
    directory mask: 777

  backup:
    path: "{{ backup_data_path }}"
    comment: Offsite backup of nas
    read only: true
    guest ok: true
    force user: nobody
