---
# grog.package role
package_list:
  - name: acl
  - name: vim
  - name: zsh
  - name: rsync
  - name: rclone
  - name: git
  - name: iptables-persistent
  - name: screen
  - name: pip # required for docker management
  - name: smartmontools
  - name: nfs-kernel-server
  - name: xfsprogs
  - name: cifs-utils
  - name: hd-idle

host_ip: "{{ vault_host_ip }}"
plex_ip: "{{ vault_plex_ip }}"
haos_ip: "{{ vault_haos_ip }}"

primary_user: jeremy
primary_group: jeremy

domain_name: "{{ base_domain_name }}"

docker_dir: /opt/docker
plex_dir: /home/{{ primary_user }}/plex

sshfs_source: "{{ vault_sshfs_source }}"
sshfs_path: /remote

# Foundry VTT
foundry_admin_key: "{{ vault_foundry_admin_key }}"
foundry_password: "{{ vault_foundry_password }}"
foundry_username: "{{ vault_foundry_username }}"
foundry_license_key: "{{ vault_foundry_license_key }}"

# Basic Auth
primary_user_htpass: "{{ vault_home_primary_user_htpass }}"

# Oauth
oauth_client_id: "{{ vault_oauth_client_id }}"
oauth_client_secret: "{{ vault_oauth_client_secret }}"
forward_auth_secret: "{{ vault_forward_auth_secret }}"
oauth_whitelist: "{{ vault_oauth_whitelist }}"

# Authelia
authelia_users: "{{ vault_authelia_users }}"
authelia_access_control: "{{ vault_authelia_access_control }}"
authelia_jwt_secret: "{{ vault_authelia_jwt_secret }}"
authelia_session_secret: "{{ vault_authelia_session_secret }}"
authelia_storage_encryption_key: "{{ vault_authelia_storage_encryption_key }}"

# Route 53
route53_access_key: "{{ vault_route53_access_key_id }}"
route53_secret_access_key: "{{ vault_route53_secret_access_key }}"
route53_region: us-west-1
route53_zone_id: "{{ vault_route53_zone_id }}"

plex_token: "{{ secret_plex_token }}"

allow_admin_rule: "{{ vault_allow_admin_rule }}"

sub_domains:
  - ai
  - ombi
  - whoami
  - oauth
  - home
  - vm
  - nas
  - nuk
  - login
  - plex
  - qbt.public
  - qbt.private
  - qbt.books
  - files
  - tautulli
  - speedtest
  - pasta
  - sonarr
  - radarr
  - readarr
  - prowlarr
  - overseerr
  - zigbee
  - index
  - unifi
  - foundry
  - factorio
  - crafty
  - vault
  - rustdeck
  - sync
