apiVersion: ENC[AES256_GCM,data:b08=,iv:ZvYWuS0ZyKo/KVCRTbOwck6Sa1IK/y8J0TDqrZSLAhw=,tag:pLph1hLvXm5IVVK7FDVyPw==,type:str]
kind: ENC[AES256_GCM,data:1ODbvvwG,iv:AaIaNfTtmBMyz9IyixQMhCO7tYTVNjGFCj5O70kRcH0=,tag:3EqWIv/0zAvoSlZX7lEjEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5aCPKuXfrlQsY7URuvDoUE3r,iv:9+hrJhayAY5oN0+Jnko7TZUARNwN1j53/qWQryALRg8=,tag:1xAYFAeB+W/8OOpwCtFIzg==,type:str]
    namespace: ENC[AES256_GCM,data:zoETcJ9/N1qc91A8,iv:oY6mj7aA91BcNZSDeyLsm+Ky2xtART22On8uoyv8YYA=,tag:w5M4mkflqom9VK2+/HHOzw==,type:str]
type: ENC[AES256_GCM,data:6vNFdN5a,iv:MYlh23by5q+aS461Yiks8PqwfP7WxOmcS0n1LkZM8ag=,tag:FRTaUcek9QB7cHIkv0Kg1g==,type:str]
stringData:
    secret-access-key: ENC[AES256_GCM,data:BejKpcHgPV4KZzjN16jUxlfcB2oz7dPz3i8=,iv:/7LT6X7zeJxUMGZDXZkuz+hvoREoJZT+bAsH3NVRMK0=,tag:0Top7zM3C0RwEbKOqJC8kw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTk03Q2VZMm0yRVNRUmFx
            K3ZiRkRLTjZqcE0zemZVK3h2WHRIeGo2RDBrCldUeG81ek5OMERLNWhCbldRWDBa
            UVY4SENaeW5od0dnTTBGVWJOdUVaQ2MKLS0tIE1SREt6WGRxZFdiYmkvdnFodW5o
            b0NzTVd4SHdqS2loOGc3YzdHVk5NQUkKoDrkNNk5T1lAPJ0NTNAkuiiwf+OE0tdR
            uNz++Tu5NzDPSBMG0bjKVGMDxbD885fp7pRozBB8OyctqN6iCRQhwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jhxcp3720dv38c2x3mc0wm2ekc20qpjhl5p0yezktt6zkwlwfpkqugp8dz
    lastmodified: "2026-06-14T19:49:01Z"
    mac: ENC[AES256_GCM,data:A9a2+OaLVW7zP5h4cjdp5xCEoqj8TwfsHmcJg8/IVVVBCZ6/F8awedkqIiTPw3QFXVasyOtG3hf0nsWenppTo4Vi0w/b5krj0YBtOoFVeIbesEBCTJNegQzp/sJCl4GrByxxG2G22e2aegY1W7lgovw5OtN8myGyy7yHHTb9zzU=,iv:tC7tKC3OOF/mo4+cumZfqDWcqoQAdLNn/BJ05ggqT8w=,tag:lNopbF64q2BLspz7sPZp5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
