---
collections:
  - name: devsec.hardening
  - name: community.docker
  - name: community.general
  - name: community.proxmox
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: main

roles:
  - name: grog.package
  - name: geerlingguy.docker
