# grog.package role
package_list:
  - "{{ required_packages }}" # stored in group_vars/all/vars.yml
  - name: mergerfs
  - name: git
  - name: snapraid
  - name: nfs-kernel-server

media_data_path: /data

plex_data_path: "{{ media_data_path }}"

disk_mount_parent: /merge

# mergerfs role
fstab_disks:
  - { src: /dev/disk/by-id/ata-WDC_WD60EFRX-68L0BN1_WD-WX61DC8H2D25-part1, path: "{{ disk_mount_parent }}/disk1", fstype: btrfs, opts: defaults, passno: 2 }
  - { src: /dev/disk/by-id/ata-TOSHIBA_HDWE150_X676KEWNF57D-part1, path: "{{ disk_mount_parent }}/disk2", fstype: xfs, opts: defaults, passno: 2 }
  - { src: /dev/disk/by-id/ata-TOSHIBA_DT01ACA300_54GYH94GS-part1, path: "{{ disk_mount_parent }}/disk3", fstype: xfs, opts: defaults, passno: 2 }
  - { src: /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAJANS1L-part1, path: "{{ disk_mount_parent }}/disk4", fstype: btrfs, opts: defaults, passno: 2 }
  - { src: /dev/disk/by-id/ata-WDC_WD60EFRX-68L0BN1_WD-WX11DA7701KY-part1, path: "{{ disk_mount_parent }}/disk5", fstype: btrfs, opts: defaults, passno: 2 }
  - { src: /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAJAKAUL-part1, path: "{{ disk_mount_parent }}/parity1", fstype: btrfs, opts: defaults, passno: 2 }
  - { src: /dev/disk/by-id/ata-WDC_WD80EFAX-68KNBN0_VAJAJMKL-part1, path: "{{ disk_mount_parent }}/parity2", fstype: btrfs, opts: defaults, passno: 2 }
  - { src: "{{ disk_mount_parent }}/disk*", path: "{{ media_data_path }}", fstype: fuse.mergerfs, opts: "defaults,allow_other,direct_io,use_ino,moveonenospc=true,minfreespace=20G,fsname=Media"}
