# ironicbadger.ansible_role_snapraid
snapraid_install: false
snapraid_runner: true

snapraid_data_disks:
  - path: "{{ disk_mount_parent }}/disk1"
    content: true
  - path: "{{ disk_mount_parent }}/disk2"
    content: true
  - path: "{{ disk_mount_parent }}/disk3"
    content: true
  - path: "{{ disk_mount_parent }}/disk4"
    content: true
  - path: "{{ disk_mount_parent }}/disk5"
    content: true
  - path: "{{ disk_mount_parent }}/disk6"
    content: true

snapraid_parity_disks:
  - path: "{{ disk_mount_parent }}/parity1"
    content: false
  - path: "{{ disk_mount_parent }}/parity2"
    content: false

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /tmp/
  - /lost+found/
  - "*.bak"
  - .AppleDouble
  - ._AppleDouble
  - .DS_Store
  - .Thumbs.db
  - .fseventsd
  - .Spotlight-V100
  - .TemporaryItems
  - .Trashes
  - .AppleDB
  - /Torrents/incomplete/
  - /Torrents/watch/
  - /Music/unsorted/
  - /.config/plex/
  - "*.!sync"

snapraid_runner_email_address: "{{ admin_email_address }}"
snapraid_runner_gmail_pass: "{{ admin_email_password }}"
#snapraid_runner_email_sendon: "error"
snapraid_runner_short: false