# grog.package role
package_list:
  - "{{ required_packages }}" # stored in group_vars/all/vars.yml
  - name: pip # required for docker management
  - name: smartmontools
  - name: nfs-kernel-server
  - name: xfsprogs
  - name: cifs-utils

host_ip: "{{ vault_host_ip }}"