---
- name: Docker Compose setup
  tags: compose-setup
  become: true
  block:
    - name: Add secrets
      ansible.builtin.include_tasks: secrets.yml
    - name: Setup Traefik
      ansible.builtin.include_tasks: traefik-setup.yml
    - name: Setup Authelia
      ansible.builtin.include_tasks: authelia.yml

    - name: Create docker-gc-exclude dir
      ansible.builtin.file:
        path: "{{ container_appdata_path }}/docker-gc/"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0700"
        state: directory

    - name: Setup docker-gc-exclude
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/clockworksoul/docker-gc-cron/master/compose/docker-gc-exclude
        dest: "{{ container_appdata_path }}/docker-gc/docker-gc-exclude"
        mode: "0600"

    - name: Create docker-gc-exclude dir
      ansible.builtin.file:
        path: "{{ container_appdata_path }}/filebrowser"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0700"
        state: directory

    - name: Create empty filebrowser.db file
      ansible.builtin.copy:
        content: ""
        dest: "{{ container_appdata_path }}/filebrowser/filebrowser.db"
        owner: "{{ primary_user }}"
        group: "{{ primary_group }}"
        force: false
        mode: "0600"

    - name: Install docker pip modules
      ansible.builtin.pip:
        name: docker-compose
        state: present
