---
- name: Docker Compose setup
  become: true
  block:
  - include_tasks: secrets.yml
  - include_tasks: traefik.yml
  - include_tasks: authelia.yml

  - name: Create docker-gc-exclude dir
    file:
      path: "{{ container_appdata_path }}/docker-gc/"
      owner: "{{ docker_user }}"
      group: "{{ docker_group }}"
      mode: 0700
      state: "directory"

  - name: Setup docker-gc-exclude
    get_url:
      url: https://raw.githubusercontent.com/clockworksoul/docker-gc-cron/master/compose/docker-gc-exclude
      dest: "{{ container_appdata_path }}/docker-gc/docker-gc-exclude"
      mode: 0600

  - name: Create docker-gc-exclude dir
    file:
      path: "{{ container_appdata_path }}/filebrowser"
      owner: "{{ docker_user }}"
      group: "{{ docker_group }}"
      mode: 0700
      state: "directory"

  - name: Create empty filebrowser.db file
    copy:
      content: ""
      dest: "{{ container_appdata_path }}/filebrowser/filebrowser.db"
      owner: "{{ primary_user }}"
      group: "{{ primary_group }}"
      force: false
      mode: 0600

  - name: install docker pip modules
    pip:
      name: docker-compose
      state: present

  tags: compose-setup