---
- name: Create 'docker/secrets' dir
  ansible.builtin.file:
    path: "{{ docker_dir }}/secrets"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0700"
    state: directory

- name: Create docker secrets
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ docker_dir }}/secrets/{{ item | basename | regex_replace('.j2', '') }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "0600"
  with_fileglob:
    - "{{ secrets_template_folder }}/*.j2"
