---
- name: Create trafick acme dir
  file:
    path: "{{ traefik_directory }}/acme"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0700
    state: "directory"

- name: Ensure 'traefik/acme/acme.json' exists
  copy:
    content: ""
    dest: "{{ traefik_directory }}/acme/acme.json"
    force: false
    mode: 0600

- name: Ensure 'traefik/traefik.log' exists
  copy:
    content: ""
    dest: "{{ traefik_directory }}/traefik.log"
    force: false
    mode: 0700

- name: Create trafick rules dir
  file:
    path: "{{ traefik_directory }}/rules"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0700
    state: "directory"

- name: Create trafik rules
  template:
    src: "{{ item }}"
    dest: "{{ traefik_directory }}/rules/{{ item | basename | regex_replace('.j2','') }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0600
  with_fileglob:
   - "{{ traefik_rules_dir }}/*.j2"
