
backup_data_path: /data

backup_mount_parent: /bak_merge
backup_disk_mount_folder: "bak_disk"
backup_mount_merge: "{{ backup_mount_parent }}/merge"

# # mergerfs role
fstab_disks:
  # Backup
  - { src: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR52QNV0-part1, path: "{{ backup_mount_parent }}/{{ backup_disk_mount_folder }}1", fstype: xfs, opts: "defaults", passno: 2  }
  - { src: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR52QWBM-part1, path: "{{ backup_mount_parent }}/{{ backup_disk_mount_folder }}2", fstype: xfs, opts: "defaults", passno: 2  }
  - { src: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR5B83ZK-part1, path: "{{ backup_mount_parent }}/{{ backup_disk_mount_folder }}3", fstype: xfs, opts: "defaults", passno: 2  }
  - { src: /dev/disk/by-id/ata-ST18000NM000J-2TV103_ZR5CBALN-part1, path: "{{ backup_mount_parent }}/parity", fstype: xfs, opts: "defaults", passno: 2  }
  #bdisk mount
  - { src: "{{ backup_mount_parent }}/{{ backup_disk_mount_folder }}*", path: "{{ backup_mount_merge }}", fstype: fuse.mergerfs, opts: "defaults,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs,moveonenospc=true,minfreespace=20G,fsname=BackupMerge,x-systemd.requires-mounts-for={{ backup_mount_parent }}/{{ backup_disk_mount_folder }}1,x-systemd.requires-mounts-for={{ backup_mount_parent }}/{{ backup_disk_mount_folder }}2,x-systemd.requires-mounts-for={{ backup_mount_parent }}/{{ backup_disk_mount_folder }}3"}
  # backup mount
  - { src: "{{ backup_mount_merge }}/disk*", path: "{{ backup_data_path }}", fstype: fuse.mergerfs, opts: "defaults,x-systemd.requires-mounts-for={{ backup_mount_merge }},allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs,moveonenospc=true,minfreespace=20G,fsname=Backup"}

# Followed these intrsuctions to disable EPC on Seagate Exos Drives
# I didn't bother making ansible do this as it's a one time thing

# Download SeaChest Utilities from Seagate here: 
# https://www.seagate.com/support/software/seachest/ 

# then run
# SeaChest_PowerControl -d /dev/(device) --EPCfeature disable
# SeaChest_PowerControl -d /dev/(device) --powerBalanceFeature disable
# You probably have to format the /dev/(device) part differently if you're on Windows (can't help you with that; I saved these directions from when I ran it on my Linux server)

# You can confirm the settings applied by running...

# SeaChest_PowerControl -d /dev/(device) --showEPCSettings
# "Current Timer" should be 0 for Idle A, Idle B, Idle C, Standby Z.

# You can list the devices with:
# SeaChest_PowerControl -s

# This will disable the head parking feature preventing a clicking noise and wear and tear on the drive.
# https://old.reddit.com/r/DataHoarder/comments/10ffsos/any_experience_with_the_seagate_exos/