---

- name: Setup stormfront docker-compose
  become: true
  block:
  - name: Setup docker-compose-files
    include_role:
      name: common/docker-compose-setup
      public: "yes"
    vars:
      authelia_logo_file: "files/assets/logo.png"
      authelia_favicon_file: "files/assets/favicon.ico"

  - name: Create {{ docker_dir }}/docker-compose.yml file
    template:
      src: docker-compose.yml.j2
      dest: "{{ docker_dir }}/docker-compose.yml"
      owner: "{{ docker_user }}"
      group: "{{ docker_group }}"
      mode: 0600

  - name: Create {{ docker_dir }}/.env file
    template:
      src: .env.j2
      dest: "{{ docker_dir }}/.env"
      owner: "{{ docker_user }}"
      group: "{{ docker_group }}"
      mode: 0600

  - name: Pull and start docker-compose configuration
    community.docker.docker_compose:
      project_src: "{{ docker_dir }}"
      remove_orphans: true
      pull: true
      state: present