---
- name: Setup stormfront docker-compose
  become: true
  block:
    - name: Setup docker-compose-files
      ansible.builtin.include_role:
        name: docker-compose-setup
        public: "yes"
      vars:
        authelia_logo_file: files/assets/logo.png
        authelia_favicon_file: files/assets/favicon.ico

    - name: Setup wireguard
      ansible.builtin.include_tasks: wireguard.yml

    - name: Create docker-compose.yml file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ docker_dir }}/docker-compose.yml"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0600"

    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: "{{ docker_dir }}/.env"
        owner: "{{ docker_user }}"
        group: "{{ docker_group }}"
        mode: "0600"

    - name: Pull and start docker-compose configuration
      community.docker.docker_compose:
        project_src: "{{ docker_dir }}"
        remove_orphans: true
        pull: true
        state: present
