- name: create folder for vpn container
  file:
    path: "{{ container_appdata_path }}/wireguard/wg_confs"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0700
    state: "directory"

- name: add wireguard conf file for container
  copy:
    src: files/vault/wg0.conf
    dest: "{{ container_appdata_path }}/wireguard/wg_confs/wg0.conf"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: 0600