# https://docs.authelia.com/configuration/access-control.html
authelia_access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.{{ domain_name }}
      policy: bypass
    # Allow access to simple apps from home network
    - domain:
        - "{{ domain_name }}"
        - "qbt.{{ domain_name }}"
        - "tautulli.{{ domain_name }}"
        - "organizr.{{ domain_name }}"
        - "files.{{ domain_name }}"
        - "whoami.{{ domain_name }}"
        #- "sonarr.{{ domain_name }}"
        #- "readarr.{{ domain_name }}"
        #- "radarr.{{ domain_name }}"
        #- "lidarr.{{ domain_name }}"
      policy: bypass
      networks:
        - 192.168.0.0/16
    - domain:
        - "{{ domain_name }}"
        - "*.{{ domain_name }}"
      policy: one_factor
      subject: "group:admins"
    - domain:
        - "{{ domain_name }}"
        - "files.{{ domain_name }}"
        - "organizr.{{ domain_name }}"
      policy: one_factor
      subject: "group:guests"

authelia_users: "{{ vault_authelia_users }}"