---
- name: Install Nvidia Drivers
  ansible.builtin.import_tasks: debian-install-nvidia.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Patch Nvidia ansible_distribution_major_version
  ansible.builtin.import_tasks: patch-driver.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
