---
- name: Git checkout nvidia-patch
  ansible.builtin.git:
    repo: https://github.com/keylase/nvidia-patch.git
    dest: /opt/nvidia-patch/
    update: true
    version: master
  notify: [Run patch.sh script]


# Commands for testing
# docker run --gpus all --rm willprice/nvidia-ffmpeg \
# -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda \
# -f lavfi -i testsrc -t 50 \
# -vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null - \
# -vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -f null - \
# -vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -f null - \
# -vf hwupload -c:a copy -c:v h264_nvenc -b:v 6M -f null -

# docker run --rm --gpus all --entrypoint nvidia-smi willprice/nvidia-ffmpeg

# docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
