
- name: Reload nmbd
  ansible.builtin.service:
    name: nmbd
    state: restarted

- name: Reload smbd
  ansible.builtin.service:
    name: smbd
    state: reloaded

- name: Restart Avahi
  ansible.builtin.service:
    name: avahi-daemon
    state: reloaded
