---

- import_tasks: debian-install-nvidia.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- import_tasks: patch-driver.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'